# permissions for end users to view pocprojects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pocproject-viewer-role
rules:
- apiGroups:
  - app.devopsico.com
  resources:
  - pocprojects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.devopsico.com
  resources:
  - pocprojects/status
  verbs:
  - get
