---
- name: "start {{ ansible_operator_meta.name }}"
  community.kubernetes.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: "{{ ansible_operator_meta.name }}-pocproject"
        namespace: "{{ ansible_operator_meta.namespace }}"
      spec:
        replicas: "{{replicas}}"
        selector:
          app: "{{ ansible_operator_meta.name }}"
        template:
          metadata:
            labels:
              app: "{{ ansible_operator_meta.name }}"
          spec:
            containers:
            - name: "{{ ansible_operator_meta.name }}-pocproject"
              image: "{{ image }}"
